In [1]:
import numpy as np
matris = np.random.randint(0, 101, size=(5, 5))
print(matris)

ortalama = np.mean(matris)
standart_sapma = np.std(matris)
varyans = np.var(matris)

print(f"\nMatrisin ortalaması: {ortalama:.2f}")
print(f"Matrisin standart sapması: {standart_sapma:.2f}")
print(f"Matrisin varyansı: {varyans:.2f}")

en_buyuk_deger = np.max(matris)
en_kucuk_deger = np.min(matris)

print(f"\nMatristeki en büyük değer: {en_buyuk_deger}")
print(f"Matristeki en küçük değer: {en_kucuk_deger}")

kosegen_toplami = np.trace(matris)

print(f"\nKöşegendeki elemanların toplamı: {kosegen_toplami}")

[[38 97 99  8 60]
 [17 51 81 13 54]
 [98 12 88 93 82]
 [16 70 23 56 89]
 [64 28 25 38 55]]

Matrisin ortalaması: 54.20
Matrisin standart sapması: 30.33
Matrisin varyansı: 919.76

Matristeki en büyük değer: 99
Matristeki en küçük değer: 8

Köşegendeki elemanların toplamı: 288


In [3]:
sinav_puanlari = np.random.normal(70, 15, 1000)
sinav_puanlari = np.clip(sinav_puanlari, 0, 100)
#örnek veriler
print("İlk 10 puan:",sinav_puanlari[:10])

ortalama = np.mean(sinav_puanlari)
medyan = np.median(sinav_puanlari)
standart_sapma = np.std(sinav_puanlari)

print(f"\nOrtalama: {ortalama:.2f}")
print(f"Medyan: {medyan:.2f}")
print(f"Standart Sapma: {standart_sapma:.2f}")

dusuk_puanlilar = sinav_puanlari < 50
dusuk_puanli_ogrenci_sayisi = np.sum(dusuk_puanlilar)
print(f"\n50'den düşük alan öğrenci sayısı: {dusuk_puanli_ogrenci_sayisi}")
      

İlk 10 puan: [65.28754982 73.02656743 69.12797625 59.0319341  58.98168984 92.71918938
 62.58938578 82.44509066 63.18864833 94.98586345]

Ortalama: 69.77
Medyan: 70.22
Standart Sapma: 14.60

50'den düşük alan öğrenci sayısı: 88


In [23]:
import pandas as pd
veri = {
    'Öğrenci': ['Ali', 'Ayşe', 'Mehmet', 'Zeynep', 'Ahmet'],
    'Yaş': [20, 21, 19, 22, 20],
    'Bölüm': ['Bilgisayar', 'Fizik', 'Kimya', 'Bilgisayar', 'Fizik'],
    'Matematik': [70, 60, 80, 90, 55],
    'Fizik': [65, 75, 70, 85, 60],
    'Kimya': [80, 85, 65, 95, 70]
}
df = pd.DataFrame(veri)

print("Oluşturulan DataFrame:\n", df)

ortalama_puanlar = df[['Matematik', 'Fizik', 'Kimya']].mean()

print("\nHer dersin ortalama puanları:\n",ortalama_puanlar )

en_yuksek_matematik = df[df['Matematik'] == df['Matematik'].max()]['Öğrenci'].iloc[0]
print("\nEn yüksek matematik notunu alan öğrenci:",en_yuksek_matematik)

df['Ortalama'] = df[['Matematik', 'Fizik', 'Kimya']].mean(axis=1)
print("\nOrtalama not sütunu eklenmiş DataFrame:\n",df)

bolumlere_gore_ortalama = df.groupby('Bölüm')[['Matematik', 'Fizik', 'Kimya', 'Ortalama']].mean()
print("\nBölümlere göre ortalama başarılar:\n",bolumlere_gore_ortalama)

basarili_ogrenciler = df[df['Ortalama'] > 70]
print("\nOrtalaması 70'in üzerinde olan öğrenciler:\n",basarili_ogrenciler)


Oluşturulan DataFrame:
   Öğrenci  Yaş       Bölüm  Matematik  Fizik  Kimya
0     Ali   20  Bilgisayar         70     65     80
1    Ayşe   21       Fizik         60     75     85
2  Mehmet   19       Kimya         80     70     65
3  Zeynep   22  Bilgisayar         90     85     95
4   Ahmet   20       Fizik         55     60     70

Her dersin ortalama puanları:
 Matematik    71.0
Fizik        71.0
Kimya        79.0
dtype: float64

En yüksek matematik notunu alan öğrenci: Zeynep

Ortalama not sütunu eklenmiş DataFrame:
   Öğrenci  Yaş       Bölüm  Matematik  Fizik  Kimya   Ortalama
0     Ali   20  Bilgisayar         70     65     80  71.666667
1    Ayşe   21       Fizik         60     75     85  73.333333
2  Mehmet   19       Kimya         80     70     65  71.666667
3  Zeynep   22  Bilgisayar         90     85     95  90.000000
4   Ahmet   20       Fizik         55     60     70  61.666667

Bölümlere göre ortalama başarılar:
             Matematik  Fizik  Kimya   Ortalama
Bölüm     