# week-3

In [9]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
notlar = set(notlar)
max_not = max(notlar)
min_not = min(notlar)
sorted_list = sorted(notlar)
print(f"maksimum not:{max_not} ve minimum not:{min_not}\n")
print(f"sıralı liste: {sorted(notlar)}")

maksimum not:100 ve minimum not:76

sıralı liste: [76, 85, 92, 100]


In [26]:
def IsArmstrong(sayi):
    toplam=0
    s=str(sayi)
    for i in range(len(s)):
        toplam += int(s[i])**3
    if toplam==sayi:
        print("Bu sayı bir Armstrong sayısıdır.")
    else:
        print("Bu sayı bir Armstrong sayısı değildir.")
IsArmstrong(245)  
IsArmstrong(153)

Bu sayı bir Armstrong sayısı değildir.
Bu sayı bir Armstrong sayısıdır.


In [37]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}
intersection = A.intersection(B)
difference = A.difference(B)
union = A.union(B)
union = list(union)
union = sorted(union)
print(f"Ortak diller:{intersection}\nSadece A’da olan diller:{difference}\nİki kümenin birleşimi:{union}")

Ortak diller:{'Python', 'SQL'}
Sadece A’da olan diller:{'R', 'Java'}
İki kümenin birleşimi:['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [46]:
import random
import statistics
sayilar=[]
for i in range(10):
    sayilar.append(random.randint(1, 100))
ortalama = statistics.mean(sayilar)
standart_sapma = statistics.stdev(sayilar)
print(f"{sayilar}\nStandart sapma ={standart_sapma:.2f}\nortalama={ortalama}")

[52, 26, 59, 11, 88, 98, 7, 81, 59, 83]
Standart sapma =32.49
ortalama=56.4


In [ ]:
def kelime_sayacı(metin):    
    kelimeler = metin.split()    
    en_uzun_kelime = max(kelimeler, key=len)      
    
    # en sık geçen kelimeyi bulmak için sözlük kullanabiliriz
    sayac={}
    for kelime in kelimeler:
        if kelime in sayac:
            sayac[kelime]+=1
        else:
            sayac[kelime] =1 #kelime ilk kez geldiği için değeri 1 yapıyorsun
    
    en_sık_gecen_kelime= max(sayac, key=sayac.get) # sözlükte kac kez gectigine bakarak maximumunu bulur
    en_sık_gecen_kelime_sayisi = sayac[en_sık_gecen_kelime]
    return len(kelimeler), en_uzun_kelime, en_sık_gecen_kelime, en_sık_gecen_kelime_sayisi

sonuc=kelime_sayacı("aaaa ne yapıyorsun nerelerdeydin hiç görüşemedik valla arada yaz ne yapıyorsun nasıl gidiyor tamam mı?")
print(sonuc)

In [68]:
sayilar = [5, 12, 7, 18, 24, 3, 16]
cift_sayilar = list(filter(lambda x: x%2==0, sayilar))
print(cift_sayilar)
sayilarin_kareleri = list(map(lambda x: x**2, sayilar))
print(sorted(sayilarin_kareleri, reverse=True ))

[12, 18, 24, 16]
[576, 324, 256, 144, 49, 25, 9]


In [72]:
# sorted(iterable, key=None, reverse=False): key: len,abs gibi neye göre sıraladığı
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
yeni_kelimeler = sorted(kelimeler, key=len, reverse=False)
print(yeni_kelimeler)
#OR
sirali_kelimeler= sorted(kelimeler, key=lambda x: len(x))
print(sirali_kelimeler)  

['veri', 'bilim', 'analiz', 'python', 'yapayzeka']
['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [91]:
# isdigit()
def isDigit(girdi):
    rakamlar=[]
    for rakam in girdi:
        if rakam.isdigit() == True:
            rakamlar.append(int(rakam))
    toplam=sum(rakamlar)
    return toplam
isDigit("fdg67e1rg8w87qewrtwe")

37

In [97]:
import numpy as np
dizi = np.random.randint(1, 51, size=10)
ortalama = np.mean(dizi)
standart_sapma = np.std(dizi)
max_deger = np.max(dizi)
print(f"Dizi={dizi},\nOrtalama:{ortalama},Standart Sapma:{standart_sapma},En büyük değer:{max_deger}")

Dizi=[14 35 39 38 31 45 31 32 25 48],
Ortalama:33.8,Standart Sapma:9.282241108697834,En büyük değer:48


In [99]:
import numpy as np
matris = np.random.rand(5, 5)
sutun_ortalamalari = np.mean(matris, axis=0)
binary_matris = np.where(matris > 0.5, 1, 0)
print(f"Matris={matris}\nSütun ortalamaları={sutun_ortalamalari}\nBinary matris={binary_matris}")


Matris=[[0.77897787 0.27059745 0.69265556 0.70490118 0.80450724]
 [0.01833198 0.49323337 0.40903107 0.1423999  0.712541  ]
 [0.30737923 0.38629807 0.92864688 0.31209158 0.28146256]
 [0.37269521 0.09284385 0.54815656 0.80169798 0.05154958]
 [0.9076464  0.36400854 0.20490667 0.8088822  0.97635178]]
Sütun ortalamaları=[0.47700614 0.32139626 0.55667935 0.55399457 0.56528243]
Binary matris=[[1 0 1 1 1]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 1 1 0]
 [1 0 0 1 1]]
